version: '3'
services:
  node-docker-dev:
    build: .
    ports:
      - '3000:3000'
    environment:
      - PORT=3000
    command: npm run dev

  mongo:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=sandro
      - MONGO_INITDB_ROOT_PASSWORD=qwerty
    volumes:
      - mongo-db:/data/db
volumes:
  mongo-db:
